### ISSUE TITLE
current versions of systemd kill WiFi

### ISSUE THREAD

**Issue by wamserma** [omgmog/archarm-usb-hp-chromebook-11#17]
The post-install.sh script updates the system, including systemd, which triggers this issue:
http://archlinuxarm.org/forum/viewtopic.php?f=60&t=8024&p=43445&hilit=systemd#p43437

Possible solutions:
* Set post-install to ignore updates to systemd until this gets somehow fixed
* Build own version of systemd with proper --configure
* Update Kernel to newer version
* give warning and/or rollback/build instructions in Readme.md

**Comment by jman6495** [comment]
https://github.com/omgmog/archarm-usb-hp-chromebook-11/pull/23
New fix to be merged

**Comment by tbepdb** [comment]
Excuse me for my language.
Several days ago i try upgrage linux kernel on my chromebook by instruction http://linux-exynos.org/wiki/HP_Chromebook_11/Installing_Linux but i used branch release-R44-7077.B-chromeos-3.8.
After instalation new kernel X server does not run, but console access and network was able.
I tried update systemd to 222, network still works. Then i downgrade systemd to 216 and lose access to console. I have to reset chromeboot to chromeos.
Maybe i allowed mistakes in kernel config and framebuffer driver was not installed.
Probably possible correct upgrade kernel to 3.8.
Anybody can try this for own risk.
