### ISSUE TITLE
Script seems to create invalid partition table ?

### ISSUE THREAD

**Issue by jman6495** [omgmog/archarm-usb-hp-chromebook-11#26]
After running the script on several USB sticks and getting the error
> WARNING: Primary GPT header is invalid                                    
>WARNING: Secondary GPT header is invalid
>Warning: /dev/sda contains GPT signatures, indicating that it has a GPT table.  However, it does not have a valid fake msdos partition table, as it should.  Perhaps it was corrupted -- possibly by a program that doesn't understand GPT partition tables.  Or perhaps you deleted the GPT table, and are now using an msdos partition table.  Is this a GPT partition table?**

I attempt to plug the USB into another computer and it reports the GPT table is corrupted.

I'm trying to understand where this error comes from. If anyone can lend a hand please do.

**Comment by jman6495** [comment]
Will rerun the same commands on my PC and see if that fixes it

**Comment by omgmog** [comment]
May be able to use `cgpt repair` to solve this.

Currently having issues with my Chromebook not wanting to power on, so I can't validate that.

Related: https://code.google.com/p/chromium/issues/detail?id=191696

**Comment by jman6495** [comment]
I'll give it a whirl ! I'm currently running the partitioning part of the script from my 64bit rig, seems to be completing without issue, so i can only think that it's chromeOS's binaries that are doing something weird ?

**Comment by omgmog** [comment]
According to that Chromium issue, the `cgpt` bundled with ChromeOS does something weird when using the `-i` command.

Unfortunately the `cgpt` man page sucks.

**Comment by jman6495** [comment]
I could recompile the latest cgpt binary if it doesn't rely on any weird libs and include it ?

**Comment by omgmog** [comment]
Adding more dependencies is fine, so long as we're in control of them -- part of the issues I've had in the past have been because of packages on AUR becoming unavailable.

We can always look at a rewrite of the main script eventually, or having an elegant way to distribute a pre-configured image (one that people can burn without issue!)

**Comment by jman6495** [comment]
I just tried using cgpt repair but i have the same issues. I'm going to try and cross compile cgpt from my pc. If that's no good i suppose the best way would be a pre-configured image, it's just hosting it (though i suppose there's sourceforge)

**Comment by starkers** [comment]
I'm happy to host it if needed (have much redundant hosting)..

I'm not much of a gpt guy but can't we simply dd a functional (minimal) gpt table onto the disk..
then format, etc... expand the final partition once booted

no need for parted/partprobe etc during the initial phases then right?

**Comment by jman6495** [comment]
@starkers  that might not be a bad idea !
I'm giving cgpt a compile and will test it locally on my chromebook in a sec, if that's no good I think that would be the best road to go down, as it eliminates the unknowns of chomeOS's binaries potentially being removed / changing

**Comment by starkers** [comment]
Aye. I'm happy to test as always

Just gate the prepare-usb.sh script a whirl (on a regular ubuntu box) and ended up with this..
```
zenbook archarm-usb-hp-chromebook-11 (master) # cgpt show /dev/sdd
       start        size    part  contents
           0           1          PMBR
           1           1          Pri GPT header
           2          32          Pri GPT table
        8192       32768       1  Label: "U-Boot"
                                  Type: ChromeOS kernel
                                  UUID: AFA8F698-3398-EE4B-ADCC-53D7976E62DD
                                  Attr: priority=10 tries=5 successful=1
       40960       32768       2  Label: "Kernel"
                                  Type: Linux data
                                  UUID: C6CEE754-D2AE-7C4F-A29E-5CBD90502C8C
      106496    15171551       3  Label: "Root"
                                  Type: Linux data
                                  UUID: D237F516-A6AA-8B40-B434-5CB412F3309D
       73728       32768      12  Label: "Script"
                                  Type: Linux data
                                  UUID: BFD34153-F54B-064F-BA97-CC54628ADA2A
    15278047          32          Sec GPT table
    15278079           1          Sec GPT header
```

Curiously enough I then zeroed first 10M and ran another show.. (after re-plugging) and it still saw the partitioning data (moans about doing a repair)..  So I'm guessing its not as straight forward as traditional paritioning.. Will do some tests/research

**Comment by jman6495** [comment]
#28  Done
