### ISSUE TITLE
Issues with ArchLinux locking up

### ISSUE THREAD

**Issue by duck** [omgmog/archarm-usb-hp-chromebook-11#27]
So, feel free to close this off if you think I should go look elsewhere.

Did the install, ran install.sh, got it on the internal drive, booted, ran the post-install.sh script, rebooted.  All good.

lightdm was missing some icons, no biggie.  The issue for me is that when the screen blanks from inactivity, I can not wake it up.  And, if I was sshed in from another machine, it will hange within a minute or so of the screen blanking out, and pings stop working to it. 

I see nothing in the logs....of course, I really don't like systemd's logging, and have not really dug deeply in to them.

Thoughts?

**Comment by jman6495** [comment]
I'll see If i can replicate it for a start! will keep you in the loop !

**Comment by duck** [comment]
cool...thanks.  Need to test the new scripts anyway...

**Comment by jman6495** [comment]
tad unrelated, but do you think it will ever be possible to get basic hardware acceleration (for OpenGLES apps) ? I may try and push to get that working too if possible. It would be awesome, especially if we could get a decent compositor working with openGLES

**Comment by omgmog** [comment]
Best thing you can do is disable the sleep time-out, and then set up sleep when you close the lid - https://blog.omgmog.net/post/making-suspend-on-lid-close-work-with-arch-linux-on-the-hp-chromebook-11/

**Comment by jman6495** [comment]
#28 Solved
