### ISSUE TITLE
IgnorePKG placed in wrong location for systemd fix, systemd upgrades regardless.

### ISSUE THREAD

**Issue by jman6495** [omgmog/archarm-usb-hp-chromebook-11#29]
This is my mistake, In the script I cat IgnorePKGs=systemd to /etc/pacman.conf, but it's in the wrong section, will commit a fix in the morning
(ps : sorry for the considerable number of notifications in the last couple of hours)

**Comment by omgmog** [comment]
As an aside, no problem about the noise -- glad that there's contribution happening! 

I added you to the contributors so you can accepts pulls directly on the main repository too.

Finally got my Chromebook to take a charge again, so I can begin working on a new process soon.

**Comment by omgmog** [comment]
We could also just explicitly add the `repo.archlinux.fr` repo to pacman.conf, rather than conditionally echoing it later.

**Comment by jman6495** [comment]
I'll do that in a bit.
Other thought : Should I download the post-install script to the root filesystem as well ? it would save downloading it afterwards !
