### ISSUE TITLE
running install.sh from usb errors

### ISSUE THREAD

**Issue by duck** [omgmog/archarm-usb-hp-chromebook-11#35]
Running the latest (as of now) install.sh script, I am hitting a couple of errors.

First, ```packer``` is not found, so I installed it via ```pacman -Syy packer```, and then re-ran the install.sh script.

Then, when the script  tries to build ```trousers```,  after editing the PKGBUILD to add the ``armv7h``, it fails with:
```
makepkg: invalid option '--asroot'
The build failed
```
The version of ``packer`` installed is ```20140810-1```

I can go create a user and build it that way, but I have to also install ```binutils`` package to get ```strip``` binary

**Comment by omgmog** [comment]
That'll be due to this change, https://github.com/keenerd/packer/issues/131

**Comment by duck** [comment]
and I needed ```gcc```, which I installed using:
```
# pacman -S --needed base-devel
```

(sorry for the stream-of-conscious updates, but I am typing as work through)

**Comment by omgmog** [comment]
So we'll need to make a non-root superuser, before we can use packer

**Comment by duck** [comment]
@omgmog yes...that would be a solution...

**Comment by duck** [comment]
missed this before.  Installing ```vboot-utils``` fails with:
```
vboot-utils:  /usr/sbin exists in filesystem
```

**Comment by omgmog** [comment]
Grab the install.sh and try again, we had some issues with conditionally executing chromeos specific commands (#36) while installing to emmc, and trying to install `cgpt` over our fixed version using pacman (#37)

**Comment by omgmog** [comment]
Okay I'm getting the same issue about `/usr/sbin` which is causing `vboot-utils` to not install.

`/usr/sbin` is a symlink to `/usr/bin`, so you might be able to just remove it and then allow `vboot-utils` to install, then re-create it.

I'll give it a go tomorrow.

**Comment by duck** [comment]
okay...my box is in a bad state...need to recover to ChromeOS, then will go for it again...

Thanks for the help, and good night!

**Comment by duck** [comment]
okay...hacked on it a bit, and the results is pull-request #39.  Feel free to nuke any/all changes. :)

**Comment by duck** [comment]
Closing due to merge of #39
