### ISSUE TITLE
USB not booting

### ISSUE THREAD

**Issue by starkers** [omgmog/archarm-usb-hp-chromebook-11#40]
Chaps thanks for the recent explosion of fixes..

I've rebuilt three different sticks and none will even try to boot. The scripts didn't report any errors when running either :/

When hitting ^u at boot it simply beeps at me, no console.

I'm still curious to figure out why a DD of a "working" usb couldn't complete its uboot but thats another issue I suppose. Please tell me if there's any info I can provide

**Comment by omgmog** [comment]
What's the size, make, model of the USB sticks you've tried? 

I've had success mostly with a 4GB HP stick.

**Comment by duck** [comment]
Actually, I had issues w/ a few HP 4G, and finally went with a 16G HP stick. :)

**Comment by jman6495** [comment]
Some USBs are incompatible with chromeos :3 I have noticed that one of mine simply doesn't work. 
Do you get any messages at boottime ?

**Comment by starkers** [comment]
So far tried a few, they're all perfectly writable within ChromOS (so says ```killall -USR1 dd```)

Sticks I have tried: (only others are <4gb)
- http://www.amazon.co.uk/dp/B00DL1M78I
- http://www.amazon.co.uk/gp/product/B0015UBSKA

Alsoa  USB-MicroSD reader (various different sized cards used)

I've been able to start the boot and get to various uboot errors before this just simply doesn't boot for me anymore. Tried zero filling one and also toggled developer mode (so that i had a clean environment again)

Doesn't seem to matter if I prep it on another machine or not either.. just weird.. main script gives no errors currently either.

Wondering if I just have a cursed model lol

If anyone would be nice enough to publish a DD of a working stick I'd be very glad!

**Comment by darev** [comment]
starkers,

I have successfully installed Arch on the HP11 using Omgmog's scripts, but like duck noted, above, I ran into a few sticks that would not boot at all, or hang early in the process. The SanDisk Cruzers (sp) I tried, two of them, would not boot on the HP11, I think I finally used a 16GB SanDisk Blade.  I don't know why some sticks just don't like to work, but try some other ones.  Sorry I don't have an image for you, I wiped the stick not too long after the install.

BTW, than you Omgmog for the great scripts.  It made this little machine much more usable.

**Comment by starkers** [comment]
Hi guys

Guess we should close this issue off.. 

I have eventually had success with a cheap "Kingston DataTraveler" USB stick my wife had kicking around.

```
ID 0951:1666 Kingston Technology
```

I used the official arch arm instructions and popped them into a script FWIW..
I don't see myself installing chromeos again but for what its worth I've put the script here:

**Comment by starkers** [comment]
Hi guys

Proud to say I'm finally running linux (proppa) on my chromebook...  The workplace gave me a shiney new expensive laptop, so.. obviously I went home and spent the night playing on my chromebook 11 instead of my new ultrabook.. 

I have eventually had success with a cheap "Kingston DataTraveler" USB stick my wife had kicking around.

```
ID 0951:1666 Kingston Technology
```

I used the official arch arm instructions from: http://archlinuxarm.org/platforms/armv7/samsung/samsung-chromebook in the end and made a script to simplify it here: https://github.com/starkers/archbook

I'd like to eventually integrate (and automate) installing the dev_install etc into that sometime but doubt I'll be booting back into chrome anytime ever again.  Thanks for all the help and details discussions here -david
