### ISSUE TITLE
http://archlinuxarm.org/os/ArchLinuxARM-chromebook-latest.tar.gz returns 404

### ISSUE THREAD

**Issue by duck** [omgmog/archarm-usb-hp-chromebook-11#48]
Looks like we have a major issue....anyone know where this got moved to?

d

**Comment by omgmog** [comment]
One of the issues of depending on an unofficial source for something. 

Might be able to try the ArmV7 build http://os.archlinuxarm.org/os/ArchLinuxARM-armv7-latest.tar.gz

My chromebook is currently in a box somewhere since I moved house, so I can't test/confirm, but if anybody wants to try this, it should be a matter of just changing `OSFILE` in https://github.com/omgmog/archarm-usb-hp-chromebook-11/blob/master/install.sh#L39

**Comment by duck** [comment]
And, I get:
```
root/boot/boot.scr.uimg               100%[========================================================================>]     349  --.-KB/s   in 0s     

2015-08-09 12:24:55 (17.4 MB/s) - 'root/boot/boot.scr.uimg' saved [349/349]

cp: cannot stat 'root/boot/vmlinux.uimg': No such file or directory
```

But, it downloads now. :)

I might have time to look at this later this week, but not today.

**Comment by hitechredneck** [comment]
duck, have any progress with this? i dragged out my chromebook and getting that pesky 404.

**Comment by duck** [comment]
I am still getting the error reported in the comment above.  Sorry.  And I have not had time to look into it.

**Comment by hitechredneck** [comment]
No worries. I'll delve deeper myself when I have time. Nice to get the dust of this thing.

**Comment by omgmog** [comment]
Have asked on the ALARM forum about the removal of the image, http://archlinuxarm.org/forum/viewtopic.php?f=47&t=9202

**Comment by omgmog** [comment]
According to the [download page](http://archlinuxarm.org/developers/downloads) the "peach" distribution is actually for Chromebooks

![](http://i.imgur.com/rFOJ0OT.png)

So perhaps changing to using that will work, providing the only change is the filename.

**Comment by omgmog** [comment]
Seems more like it, the Exynos5 is also called "Peach Pit" and "Peach Pi" [1], so I assume this "peach" distro applies to both.

1 - https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/samsung-chromebook-2#TOC-Peach-Pit-XE503C12-

**Comment by omgmog** [comment]
Okay as further confirmation, the Samsung Chromebook instructions on the ALARM wiki now refer to the peach image, so this is correct.

I've updated the OSFILE reference in install.sh (https://github.com/omgmog/archarm-usb-hp-chromebook-11/commit/c8708e4da66e33632fd0c3e8c9f826b8bfed9758) so this can be closed.

**Comment by valntin** [comment]
I am getting:

cp: cannot stat 'root/boot/vmlinux.uimg': No such file or directory

**Comment by starkers** [comment]
Ye man thats a known issue, see: https://github.com/omgmog/archarm-usb-hp-chromebook-11/issues/49

If you're desperate install arch with [this](https://github.com/starkers/archbook) (and please report back success/failure and which USB stick you have)

**Comment by garynichols** [comment]
Confirmed that https://github.com/starkers/archbook works like a champ to install to both USB (I used a SanDisk Cruzer 8GB) and to mmc.  I have it up and running from mmc on my HP CB11 finally!!  Works great.

**Comment by omgmog** [comment]
Yep I suggest people use @starkers' script from now on :)

**Comment by wamserma** [comment]
I second that. Maybe reference that in the README.md,

**Comment by omgmog** [comment]
Good idea, I've now done that in ed553b3583b2481438468a8669984123834f7e98
